name: CI

on:
  push:
    branches: [main]
    
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3.3.0
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.USER }}
          password: ${{secrets.PASSWD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: .
          push: true
          tags: |
            andradeleandro/teste2:v1
            andradeleandro/teste2:latest
            
